spring.application.name=DeOlhoNoLixo

spring.datasource.url=${POSTGRES_DB}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

spring.data.mongodb.uri=${MONGO_DB_URI}
spring.data.mongodb.database=${MONGO_DB}
spring.data.mongodb.auto-index-creation=true

api.security.token.secret=${SECRET_KEY_TOKEN}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_EMAIL}
spring.mail.password=${SMTP_EMAIL_APP_KEY}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000